stages:
  - Staging
  - Production

Staging:
  variables:
    CLUSTERGCP: test
    LOCATION: asia-southeast2-a
  stage: Staging
  image: google/cloud-sdk
  services:
    - docker:dind
  script:
    - cat $VARSSTAG > .env
    - echo $GCP_SERVICE_KEY > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud builds submit --config=cloudbuild.yml --substitutions=_CI_PROJECT_TITLE=$CI_PROJECT_TITLE,_CLUSTERIN=$CLUSTERGCP,_LOCATIONCLUSTER=$LOCATION
  only:
    - /^release/.*$/i

Production:
  variables:
    CLUSTERGCP: gramediadigital-production
    LOCATION: asia-southeast1
  stage: Production
  image: google/cloud-sdk
  services:
    - docker:dind
  script:
    - cat $VARSPROD > .env
    - sed -i 's|staging|$_CI_COMMIT_SHA|g' cloudbuild.yml
    - sed -i 's|staging|$_CI_COMMIT_SHA|g' deployment.yml
    - echo $GCP_SERVICE_KEY > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud builds submit --config=cloudbuild.yml --substitutions=_CI_PROJECT_TITLE=$CI_PROJECT_TITLE,_CLUSTERIN=$CLUSTERGCP,_CI_COMMIT_SHA=$CI_COMMIT_SHA,_LOCATIONCLUSTER=$LOCATION
  when: manual
  only:
    - /^release/.*$/i
