stages:
  #- Sonarcloud
  - Staging
  - Production

Staging:
  variables:
    CLUSTERGCP: test
    LOCATION: asia-southeast1
  stage: Staging
  image: google/cloud-sdk
  services:
    - docker:dind
  script:
    - cat $VARSSTAG > .env
    - echo $GCP_SERVICE_KEY > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud builds submit --config=cloudbuild.yml --substitutions=_CI_PROJECT_TITLE=$CI_PROJECT_TITLE,_CLUSTERIN=$CLUSTERGCP,_CI_COMMIT_SHA=$CI_COMMIT_SHA,_LOCATIONCLUSTER=$LOCATION
  only:
    - feature/add-mmodal

#Sonarcloud:
#  stage: Sonarcloud
#  image:
#    name: sonarsource/sonar-scanner-cli:latest
#    entrypoint: [""]
#  variables:
#    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
#    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
#  cache:
#    key: "${CI_JOB_NAME}"
#    paths:
#      - .sonar/cache
#  script:
#    - sonar-scanner
#  when:
#   - manual
#  only:
#    - merge_requests
#    - master

Production:
  variables:
    CLUSTERGCP: gramediadigital-production
    LOCATION: asia-southeast2-a
  stage: Production
  image: google/cloud-sdk
  services:
    - docker:dind
  script:
    - cat $VARSPROD > .env
    - echo $GCP_SERVICE_KEY > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud builds submit --config=cloudbuild.yml --substitutions=_CI_PROJECT_TITLE=$CI_PROJECT_TITLE,_CLUSTERIN=$CLUSTERGCP,_CI_COMMIT_SHA=$CI_COMMIT_SHA,_LOCATIONCLUSTER=$LOCATION
 
  #needs:
  #  - job: Sonarcloud
#  when: manual
  only:
    - /^release/.*$/i
