apiVersion: apps/v1
kind: Deployment
metadata:
  name: revamp-web-reader
spec:
  selector:
    matchLabels:
      app: revamp-web-reader
  template:
    metadata:
      labels:
        app: revamp-web-reader
    spec:
      containers:
        - name: server
          image: gcr.io/gramedia-digital-5a7c5/revamp-web-reader:staging
          ports:
          - containerPort: 3000